---
title: 'Analysis'
output:
  distill::distill_article:
    toc:false:
      theme: theme.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

```{r include = FALSE}
library(tidyverse)
library(doParallel)
library(R.utils)
library(reactable)
library(rio)
library(htmltools)
options(digits = 7)
registerDoParallel()
getDoParWorkers()
```

### Crime (group A) frequency by type in each neighborhood

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.width=10,fig.height=5, layout="l-body-outset"}
c_nh <- import("data/nibrs_crime_nh.csv")
table_out <- reactable(
    c_nh,
    defaultColDef = colDef(
      header = function(value) gsub(".", " ", value, fixed = TRUE),
      cell = function(value) format(value, nsmall = 1),
      align = "center",
      minWidth = 200,
      headerStyle = list(background = "#f7f7f8")
    ),
    columns = list(
      Species = colDef(minWidth = 200)  # overrides the default
    ),
    bordered = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    searchable = TRUE
  )
  
  withtitle <- htmlwidgets::prependContent(table_out, 
                                           h2(class = "title", paste("Crime (group A) frequency by type in each neighborhood")),
                                           font=list(size=5))
withtitle
```

### Crime (group A) frequency by category in each neighborhood

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.width=10,fig.height=5, layout="l-body-outset"}
c_nh <- import("data/nibrs_crime_category_nh.csv")
table_out <- reactable(
    c_nh,
    defaultColDef = colDef(
      header = function(value) gsub(".", " ", value, fixed = TRUE),
      cell = function(value) format(value, nsmall = 1),
      align = "center",
      minWidth = 200,
      headerStyle = list(background = "#f7f7f8")
    ),
    columns = list(
      Species = colDef(minWidth = 200)  # overrides the default
    ),
    bordered = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    searchable = TRUE
  )
  
  withtitle <- htmlwidgets::prependContent(table_out, 
                                           h2(class = "title", paste("Crime (group A) frequency by category in each neighborhood")))
withtitle
```

### Crime (group A) frequency by type in each zipcode

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.width=10,fig.height=5, layout="l-body-outset"}
c_zip <- import("data/nibrs_crime_zip.csv")
table_out <- reactable(
    c_zip,
    defaultColDef = colDef(
      header = function(value) gsub(".", " ", value, fixed = TRUE),
      cell = function(value) format(value, nsmall = 1),
      align = "center",
      minWidth = 200,
      headerStyle = list(background = "#f7f7f8")
    ),
    columns = list(
      Species = colDef(minWidth = 200)  # overrides the default
    ),
    bordered = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    searchable = TRUE
  )
  
  withtitle <- htmlwidgets::prependContent(table_out, 
                                           h2(class = "title", paste("Crime (group A) frequency by type in each zipcode")))
withtitle
```

### Crime (group A) frequency by category in each zipcode

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.width=10,fig.height=5, layout="l-body-outset"}
c_zip <- import("data/nibrs_crime_category_zip.csv")
table_out <- reactable(
    c_zip,
    defaultColDef = colDef(
      header = function(value) gsub(".", " ", value, fixed = TRUE),
      cell = function(value) format(value, nsmall = 1),
      align = "center",
      minWidth = 200,
      headerStyle = list(background = "#f7f7f8")
    ),
    columns = list(
      Species = colDef(minWidth = 200)  # overrides the default
    ),
    bordered = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    searchable = TRUE
  )
  
  withtitle <- htmlwidgets::prependContent(table_out, 
                                           h2(class = "title", paste("Crime (group A) frequency by category in each zipcode")))
withtitle
```


# Data

The weekly PAI data is available at [https://github.com/farbodcpal/PAI_analysis/tree/main/data](https://github.com/farbodcpal/PAI_analysis/tree/main/data)

# Predictive Accuracy Index 

Below, the PAI of each division is visualized over time since 08/01/2022
