---
title: 'Analysis Part 5'
output:
  distill::distill_article:
    toc:false:
      theme: theme.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

```{r include = FALSE}
library(tidyverse)
library(doParallel)
library(R.utils)
library(reactable)
library(rio)
library(sf)
library(htmltools)
library(chron)
library(lubridate)
options(digits = 7)
registerDoParallel()
getDoParWorkers()
```

```{r include=FALSE}
libDB <- "D:/SMU/Ph.D/CPAL/"
masterODP_CPAL <- import("D:/SMU/Ph.D/CPAL/Open Data Portal Incidents/Data/Incidents/Processed Data/Dallas Police Incidents - All Incidents Since Aug 2019.csv") 
arrests <- import("D:/SMU/Ph.D/CPAL/Open Data Portal Incidents/Data/Incidents/Processed Data/Dallas Police Arrests - All Arrests.csv") %>% 
  dplyr::select(incidentnum, arrestnumber, ararrestdate, ararresttime, arpremises)

neighborhood <- st_read(paste0(libDB, "New Model Development/Geopackage/Neighborhoods.gpkg"), layer = "bc_neighborhoods") %>%
  st_transform(crs = 2276)

firearm <- c("Handgun", "Rifle","Firearm (Type Not Stated)", "Assault Weapon", "Unknown Type Gun", "Other/Unknown Gun", "Shotgun", "Other Gun", "Other Firearm")
vgc_type <- c("AGG ASSAULT - NFV", "MURDER & NONNEGLIGENT MANSLAUGHTER", "NEGLIGENT MANSLAUGHTER")

masterODP_arrests <- masterODP_CPAL %>% left_join(., arrests) %>%
  mutate(Date = as.Date(Date),
         Time = lubridate::hm(Time),
         Year = year(Date),
         Month = month(Date),
         Day = day(Date),
         division = str_to_title(division),
         crime_category = as.factor(nibrs_crime_category),
         crime = as.factor(nibrs_crime),
         Weekday = wday(Date),
         DateTime = format(paste(Date, Time), format="%Y-%m-%d %H:%M:%S"),
         vgc_flag = ifelse(nibrs_crime %in% vgc_type & Firearm == 1, 1, 0)) %>%
  mutate(crime_title = ifelse(crime == "MURDER & NONNEGLIGENT MANSLAUGHTER", "Murder & Nonnegligent Manslaughter",
                              ifelse(crime == "VIOLENT GUN CRIME", "Violent Gun Crime",
                                     ifelse(crime == "AGG ASSAULT - NFV", "Aggravated Assault (NFV)",
                                            ifelse(crime == "ROBBERY-BUSINESS", "Robbery (Business)",
                                                   ifelse(crime == "ROBBERY-INDIVIDUAL", "Robbery (Individual)",
                                                          ifelse(crime == "BURGLARY-RESIDENCE", "Burglary (Residence)",
                                                                 ifelse(crime == "BURGLARY-BUSINESS", "Burglary (Business)",
                                                                        "ERROR"
                                                                 ))))))))  %>%
  select(incidentnum:premise, incident_address:time1, reporteddate, involvement:ro1name, status, mo, offensecode:nibrs_type, zip_code:geocoded_column.longitude, taag:compsex, weaponused, tot_victims:crime_title) %>%
  #filter(crime %in% c("MURDER & NONNEGLIGENT MANSLAUGHTER", "AGG ASSAULT - NFV", "ROBBERY-BUSINESS", "ROBBERY-INDIVIDUAL", "BURGLARY-RESIDENCE", "BURGLARY-BUSINESS")) %>%
  mutate(ArDate = as.Date(ararrestdate),
         ArLength = time_length(ArDate-Date, unit = "days"),
         ArOccur = ifelse(is.na(arrestnumber), "NO", "YES"))

# Keeping only incidents that arrest happened
masterODP_with_arrests <- masterODP_arrests %>% drop_na(arrestnumber)

# Convert dataframe into sf geographic files with 4202 projection
crime_neighbor <- st_as_sf(x = masterODP_arrests, coords = c(x = "x_coordinate", y = "y_coordinate"), crs = 2276)
crime_neighbor <- crime_neighbor[neighborhood,]

#neinames <- c("Oak Lawn", "Uptown", "Pleasant Grove", "Bachman", "Vickery Meadow(s)")

p_func <- function(neighbor_name){
  
  neighborhood_subset <- neighborhood %>% dplyr::filter(NeighName == neighbor_name)
  crime_neighbor_subset <- crime_neighbor[neighborhood_subset,]
  
  crime_count <- crime_neighbor_subset %>% dplyr::filter(Year == 2022)
  crime_per_month <- round(nrow(crime_count)/12, 0)
  crime_per_week <- round(nrow(crime_count)/52, 0)
  
  a <- ((table(crime_neighbor_subset$Year, crime_neighbor_subset$Month)))
  b <- data.frame(colMeans(a[2:4,])) %>% mutate(Var1 = "Average", Var2 = c(1:12)) %>% rename(Freq = colMeans.a.2.4.... ) %>% 
    relocate(Var1, .before = Freq) %>% relocate(Var2, .before = Freq)
  a <- data.frame(a) %>% dplyr::filter(Var1 != 2019)
  a <- rbind(a,b)
  a$Freq[a$Freq == 0] <- NA
  
  data1 <- a %>% dplyr::filter(Var1 == "Average")
  data2 <- a %>% dplyr::filter(Var1 == 2022)
  
  p <- ggplot(NULL, aes(Var2, Freq)) + 
    geom_line(data = data1, aes(color='Last 3 Years', group=1)) +
    geom_line(data = data2, aes(color='2022', group=1)) + ylab("Frequency") + xlab("Month") + 
    ggtitle(paste( "All Crime Incidents per Month at", neighbor_name)) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 9)) +
    scale_color_manual(name='Legend',
                       breaks=c('Last 3 Years', '2022'),
                       values=c('Last 3 Years'='red', '2022'='blue')) + theme(
                         legend.position = c(0.02, .95),
                         legend.justification = c("left", "top"),
                         legend.box.just = "left",
                         legend.margin = margin(6, 6, 6, 6)
                       )  +  annotate(geom="text", x=max(as.numeric(data2$Var2)), y=max(as.numeric(data2$Freq), na.rm = T) +4, label=paste(crime_per_month, "Crime Per Month in 2022"),color="red", size = 3, hjust=1) + 
                             annotate(geom="text", x=max(as.numeric(data2$Var2)), y=max(as.numeric(data2$Freq), na.rm = T) +16, label=paste(crime_per_week, "Crime Per Week in 2022"),color="red", size = 3, hjust=1)

  return(p)
}
  
p2_func <- function(neighbor_name){
  
  neighborhood_subset <- neighborhood %>% dplyr::filter(NeighName == neighbor_name)
  crime_neighbor_subset <- crime_neighbor[neighborhood_subset,]
  
  
  arrests <- crime_neighbor_subset %>% drop_na(arrestnumber)
  month_tbl <- arrests %>%
    group_by(Year, Month) %>%
    summarize(arrestCount = n()) %>%
    ungroup(.) %>%
    mutate(Date = as.Date(paste0(Year, "-", Month, "-01")),
           monthAvg = zoo::rollmean(arrestCount, k = 3, fill = NA))
  
  
  p2 <- month_tbl %>% ggplot(aes(x = Date, y = arrestCount)) +
    geom_col(fill = "#595959",
             alpha = 0.5) +
    geom_line(aes(y = monthAvg),
              color = "#ffffff",
              size = 2) +
    geom_line(aes(y = monthAvg),
              color = "#e98816",
              size = 1) +
    labs(
      title = paste( "Arrests by Month at", neighbor_name),
      subtitle = "Relative to 3 Month Average",
      x = "",
      y = "",
      color = 'VARIABLE'
    )
  return(p2)
}


tbl_func <- function(neighbor_name){
  
  neighborhood_subset <- neighborhood %>% dplyr::filter(NeighName == neighbor_name)
  crime_neighbor_subset <- crime_neighbor[neighborhood_subset,]
  
  table_crime <- crime_neighbor_subset %>% dplyr::filter(Year != 2019)
  top_incidents_tab <- data.frame(table(table_crime$nibrs_crime_category))
  top_incidents_tab <- top_incidents_tab  %>% arrange(desc(`Freq`)) %>% slice(1:5) %>% rename(`Crime Type` = Var1, "Frequency" = Freq )
  table_out <- reactable(
    top_incidents_tab,
    defaultColDef = colDef(
      header = function(value) gsub(".", " ", value, fixed = TRUE),
      cell = function(value) format(value, nsmall = 1),
      align = "center",
      minWidth = 100,
      headerStyle = list(background = "#f7f7f8")
    ),
    columns = list(
      Species = colDef(minWidth = 200)  # overrides the default
    ),
    bordered = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    searchable = TRUE
  )
  
  withtitle <- htmlwidgets::prependContent(table_out, 
              h2(class = "title", paste("Top 10 Crime Types In the Last Three Years at", neighbor_name)))
  
  return(withtitle)
}
```

## Top 10 Crime Types In the Last Three Years, All Crime Incidents per Month, and Arrests by Month in the top 5 neighborhood with the most crimes

### Oak Lawn

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.width=10,fig.height=5, layout="l-body-outset"}
p_func("Oak Lawn")
p2_func("Oak Lawn")
tbl_func("Oak Lawn")
```

### Uptown

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.width=10,fig.height=5, layout="l-body-outset"}
p_func("Uptown")
p2_func("Uptown")
tbl_func("Uptown")
```
"", "Bachman", "Vickery Meadow(s)"
### Pleasant Grove

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.width=10,fig.height=5, layout="l-body-outset"}
p_func("Pleasant Grove")
p2_func("Pleasant Grove")
tbl_func("Pleasant Grove")
```

### Bachman

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.width=10,fig.height=5, layout="l-body-outset"}
p_func("Bachman")
p2_func("Bachman")
tbl_func("Bachman")
```

### Vickery Meadow(s)

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.width=10,fig.height=5, layout="l-body-outset"}
p_func("Vickery Meadow(s)")
p2_func("Vickery Meadow(s)")
tbl_func("Vickery Meadow(s)")
```


